### ISSUE TITLE
Google QR code generator deprecated

### ISSUE THREAD

**Issue by headyj** [lisenet/docker-openvpn#25]
Hello,

It seems that google API generating the OTP code has been deprecated and is not working anymore: https://chart.googleapis.com/chart (see https://developers.google.com/chart/infographics/docs/qr_codes?hl=fr)

There are multiple alternatives for generating QR codes, one of them being https://quickchart.io/qr-code-api/

**Comment by lisenet** [comment]
Is this for `pam_google_authenticator`? I never used that functionality to be fair.

I've have my OpenVPN server integrated with [Duo MFA](https://duo.com/editions-and-pricing/duo-free) (the free version).

**Comment by headyj** [comment]
This is the functionality to generate a qr code for strong auth. The qr code generation itself is working but the URL is not valid anymore.

I know it's somewhere around here but didn't had the time to investigate on how it's actually working: https://github.com/lisenet/docker-openvpn/blob/master/bin/ovpn_otp_user

**Comment by lisenet** [comment]
Is it a _form_ of MFA then? A second factor required in order to log in? I never used that functionality therefore not entirely sure what use case it is for.

**Comment by headyj** [comment]
It generates a second factor in order to login yes. I still use the tool from the original kylemanna/docker-openvpn repo: https://github.com/kylemanna/docker-openvpn/blob/master/docs/otp.md

**Comment by lisenet** [comment]
OK, no worries, that's good to know. I won't have the capacity to look into this as I don't use the feature, however, if you'd like to raise a PR that would be appreciated.

**Comment by headyj** [comment]
OK, actually the generated data is still working (as expected) but the link is the only issue, so it's not really blocking. I will try to do a PR but I can't guarantee.
