### ISSUE TITLE
Don't work with host using nft tables kernel 

### ISSUE THREAD

**Issue by Poueck** [lisenet/docker-openvpn#28]
Trying to use on Alma Linux 9, I got the following error logs:
`openvpn-tcp-1  | iptables v1.8.10 (legacy): can't initialize iptables table 'nat': Table does not exist (do you need to insmod?)`
`openvpn-tcp-1  | Perhaps iptables or your kernel needs to be upgraded.`
`openvpn-tcp-1 exited with code 0`

iptables (legacy) are used instead of iptables-nft.

Would be great if the container auto-detect the correct iptables commands to use.

Best Regards,

Poueck

**Comment by lisenet** [comment]
This is very likely due to this: https://github.com/lisenet/docker-openvpn/issues/4

**Comment by Poueck** [comment]
Hi, thanks for your response.
I will look on your link.

As a workaround, I forked the project and have modifier the Dockerfile to remove the installation of iptables-legacy. Then it works on my server, but have not tested on an iptables legacy server.

Regards,
Poueck.

**Comment by lisenet** [comment]
I think the time has come to stop supporting `iptables-legacy`. The world has moved on to `iptables-nft` (RHEL 8/9, Ubuntu 22.04/24.04).
